version: "2"
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
        - "27017:27017"